inherit_from: base
test_data_args:
  sequence_args:
    grid_world_args:
      n_maze: 0
      p_wall: 0
    omit_states_actions: 0
train_data_args:
  sample_from_trajectories: true
  sequence_args:
    episode_length: 20
    grid_world_args:
      n_maze: 0
      p_wall: 0
    n_episodes: 10
