data_args:
  grid_world_args:
    absorbing_state: true
    dense_reward: false
    gamma: 0.99
    grid_size: 4
    heldout_goals: []
    p_wall: 0
    terminate_on_goal: false
    use_heldout_goals: false
  n_data: 100_000
  n_pi_bins: 2
  omit_states_actions: 0
  stop_at_rmse: 0.005
data_path: "data/sample_uniform"
decay_args:
  final_step: 200_000
  warmup_steps: 10_000
load_path: null
loss: "mse"
lr: 0.001
max_test: 2000
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 128
  n_isab: 0
  n_sab: 2
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
n_batch: 50
n_epochs: 100
save_interval: 40000
seed: 0
test_1_interval: 100
test_n_interval: 200
test_split: 0.02
train_1_interval: 100
train_n_interval: 200
