bellman_delta: 2
data_args:
  q_load_path: null
  sample_from_trajectories: false
  sequence_args:
    grid_world_args:
      absorbing_state: true
      dense_reward: false
      gamma: 0.99
      grid_size: 4
      heldout_goals: []
      terminate_on_goal: true
      use_heldout_goals: false
    stop_at_rmse: 0.005
decay_args:
  final_step: 500_000
  warmup_steps: 10_000
evaluate_args:
  accuracy_threshold: 0.01
load_path: null
lr: 0.0002
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 512
  n_isab: 0
  n_sab: 3
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
n_batch: 50
n_epochs: 2000
n_plot: 3
save_interval: 40000
seed: 0
test_1_interval: ${train_1_interval}
test_data_args:
  dataset_args:
    max_n_bellman: 1
  sequence_args:
    grid_world_args:
      n_maze: 200
      n_tasks: 200
      p_wall: 1
test_n_interval: ${train_1_interval}
train_1_interval: 1000
train_data_args:
  dataset_args:
    max_n_bellman: null
  sequence_args:
    grid_world_args:
      n_maze: 0
      n_tasks: 80_000
      p_wall: 0.25
value_conditional: true
