data_args:
  sequence_args:
    omit_states_actions: 0
inherit_from: base
test_data_args:
  sequence_args:
    grid_world_args:
      n_maze: 0
      p_wall: 0
train_data_args:
  sequence_args:
    grid_world_args:
      n_maze: 0
      p_wall: 0
