data_args:
  sequence_args:
    grid_world_args:
      absorbing_state: false
inherit_from: base
test_data_args:
  sequence_args:
    grid_world_args:
      n_maze: 0
      p_wall: 0
    omit_states_actions: 0
train_data_args:
  sample_from_trajectories: true
  sequence_args:
    grid_world_args:
      n_maze: 0
      p_wall: 0
    trajectory_length: 200
