agent_args:
  hidden_size: 512
  recurrent: false
disable_gae: false
disable_linear_lr_decay: false
disable_proper_time_limits: false
dummy_vec_env: false
env_args: {}
gae_lambda: 0.95
gamma: 0.99
load_path: null
log_interval: 1
lr: 3e-4
num_processes: 1
num_steps: 2048
num_updates: 1000
optim_args:
  eps: 1e-5
save_interval: 5
seed: 1
update_args:
  clip_param: 0.2
  entropy_coef: 0
  max_grad_norm: 0.5
  num_mini_batch: 32
  ppo_epoch: 10
  value_loss_coef: 0.5
use_replay_buffer: false
