data_args:
  sequence_args:
    grid_world_args:
      absorbing_state: true
      dense_reward: false
      gamma: 0.99
      grid_size: 4
      heldout_goals: []
      n_maze: 0
      p_wall: 0
      stop_at_rmse: 0.005
      terminate_on_goal: true
      use_heldout_goals: false
    omit_states_actions: 0
decay_args:
  final_step: 200_000
  warmup_steps: 10_000
evaluate_args:
  accuracy_threshold: 0.01
load_path: null
lr: 0.001
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 128
  n_isab: 0
  n_sab: 2
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
n_batch: 50
n_epochs: 100
n_plot: 3
save_interval: 40000
seed: 0
test_1_interval: ${train_1_interval}
test_data_args:
  dataset_args:
    max_initial_bellman: 1
  sequence_args:
    n_data: 200
  sample_from_trajectories: false
test_n_interval: ${train_1_interval}
train_1_interval: 1000
train_data_args:
  dataset_args:
    max_initial_bellman: null
  sequence_args:
    episode_length: 20
    n_data: 80_000
    n_episodes: 10
  sample_from_trajectories: true
