data_args:
  n_pi_bins: 3
  n_policies: 100_000
  order_delta: 1
decay_args:
  final_step: 200_000
  warmup_steps: 4000
load_path: null
log_interval: 20
loss: "mse"
max_layers: 10
min_layers: 1
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 128
  sab_args:
    ln: false
    n_heads: 8
n_batch: 50
n_epochs: 50000
save_interval: 40000
seed: 0
test_interval: 1000
test_split: 0.02
