data_args:
  n_input_bins: 20
  n_output_bins: 10_000
  n_steps: 100_000
load_path: null
log_freq: 20
max_layers: 10
min_layers: 1
n_batch: 50
n_epochs: 500
save_freq: 400
seed: 0
test_freq: 100
test_split: 0.02
