data_args:
  include_v1: true
  max_order: null
  min_order: null
  n_input_bins: 1000
  n_output_bins: 10
  n_policies: 128
log_freq: 20
max_layers: 10
min_layers: 1
n_batch: 50
n_epochs: 50
n_steps: 100_000
run_name: "trial"
save_freq: 400
seed: 0
test_freq: 100
test_split: 0.02
