data_args:
  include_v1: true
  max_order: null
  min_order: null
  n_input_bins: 10
  n_output_bins: 100
  n_policies: null
load_path: null
log_freq: 20
max_layers: 10
min_layers: 1
n_batch: 50
n_epochs: 500
n_steps: 100_000
save_freq: 400
seed: 0
test_freq: 100
test_split: 0.02
