data_args:
  n_pi_bins: 3
  n_policies: 100_000
  n_v1_bins: 10_000
  n_v2_bins: 10_000
load_path: null
log_freq: 20
max_layers: 10
min_layers: 1
n_batch: 50
n_epochs: 500
save_freq: 40000
seed: 0
test_freq: 100
test_split: 0.02
