data_args:
  n_pi_bins: 3
  n_policies: 100_000
decay_args:
  final_step: 200_000
  warmup_steps: 4000
load_path: null
log_interval: 200
loss: "mse"
lr: 0.001
max_layers: 10
min_layers: 1
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 128
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
n_batch: 50
n_epochs: 50000
order_delta: 1
save_interval: 40000
seed: 0
test_1_interval: 100
test_n_interval: 200
test_split: 0.02
