evaluator_args:
  rollout_length: ${trajectory_length}
grid_world_args:
  absorbing_state: false
  dense_reward: false
  gamma: 0.99
  grid_size: 2
  heldout_goals: []
  n_maze: 0
  p_wall: 0
  terminate_on_goal: true
  use_heldout_goals: false
inherit_from: base
partial_observation: false
time_limit: null
train_size: 1000
trajectory_length: 64
use_exploration_policy: false
