inherit_from: value-conditional
test_data_args:
  sequence_args:
    grid_world_args:
      grid_size: 5
      n_maze: 0
      p_wall: 0
    omit_states_actions: 0
train_data_args:
  sequence_args:
    grid_world_args:
      grid_size: 5
      n_maze: 0
      p_wall: 0
    omit_states_actions: 52
