disable_gae: false
disable_linear_lr_decay: false
disable_proper_time_limits: false
dummy_vec_env: true
env_name: MiniWorld-OneRoomS6Fast-v0
gae_lambda: 0.95
gamma: 0.99
inherit_from: base
load_path: null
log_interval: 1
lr: 3e-4
num_processes: 1
num_steps: 2048
num_updates: 1
optim_args:
  eps: 1e-5
recurrent_policy: false
seed: 1
test_size: 20
train_args:
  count_threshold: 10
trajectory_length: 256
update_args:
  clip_param: 0.2
  entropy_coef: 0
  max_grad_norm: 0.5
  num_mini_batch: 32
  ppo_epoch: 10
  value_loss_coef: 0.5
use_grid_world: false
