dummy_vec_env: true
env_args:
  env_name: MiniWorld-OneRoomS6Fast-v0
gamma: 0.99
inherit_from: base
load_path: null
log_interval: 1
lr: 5e-4
optim_args:
  eps: 1e-5
ppo_args:
  disable_gae: false
  disable_linear_lr_decay: false
  disable_proper_time_limits: false
  dummy_vec_env: true
  gae_lambda: 0.95
  lr: 3e-4
  num_processes: 10
  num_steps: 2048
  num_updates: 1
  recurrent_policy: false
  update_args:
    clip_param: 0.2
    entropy_coef: 0
    max_grad_norm: 0.5
    num_mini_batch: 32
    ppo_epoch: 10
    value_loss_coef: 0.5
seed: 1
test_size: 20
train_args:
  count_threshold: 10
  n_batch: 50
trajectory_length: 256
use_grid_world: false
