lr: 0.001
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 256
  n_isab: 0
  n_sab: 3
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
n_plot: 1
rmse_bellman: 0.005
rmse_training_final: 0.001
rmse_training_intermediate: 0.005
seed: 3
sequence_args:
  grid_world_args:
    absorbing_state: true
    dense_reward: false
    gamma: 0.99
    grid_size: 4
    heldout_goals: []
    n_maze: 0
    p_wall: 0.25
    stop_at_rmse: 0.005
    terminate_on_goal: true
    use_heldout_goals: false
  n_data: 80_000
  omit_states_actions: 0
  sample_from_trajectories: false
  seed: 0
test_size: 50
train_args:
  decay_args:
    final_step: 500_000
    warmup_steps: 10_000
  evaluate_args:
    accuracy_threshold: 0.01
  log_interval: 50
  n_batch: 50
  test_interval: 1000
value_conditional: false
