bellman_delta: 1
lr: 0.0005
partial_observation: false
rmse_bellman: 0.005
rmse_training_final: 0.002
rmse_training_intermediate: 0.005
seed: 3
sequence_args:
  grid_world_args:
    dense_reward: false
    gamma: 0.99
    heldout_goals: []
    n_maze: 0
    terminate_on_goal: true
    use_heldout_goals: false
  seed: 0
  stop_at_rmse: 0.005
test_size: 50
train_args:
  decay_args:
    final_step: 500_000
    warmup_steps: 10_000
  evaluate_args:
    accuracy_threshold: 0.01
  log_interval: 50
  test_interval: 1000
value_conditional: false
