inherit_from: base
model_args:
  n_heads: 8
  n_hidden: 256
  n_layers: 3
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
model_type: gpt2
n_plot: 3
sample_from_trajectories: true
sequence_args:
  episode_length: 64
  grid_world_args:
    absorbing_state: false
    grid_size: 2
    n_tasks: 250
    p_wall: 0
  n_episodes: 1
  use_exploration_policy: false
train_args:
  alpha: .5
  n_batch: 250
  n_rotations: 4
