inherit_from: base
model_args:
  isab_args:
    n_inds: 32
  n_hidden: 256
  n_isab: 0
  n_sab: 3
  positional_encoding_args:
    log_term: 10000.0
    scale_term: 1000
  sab_args:
    ln: true
    n_heads: 8
model_type: set
n_plot: 1
sample_from_trajectories: false
sequence_args:
  grid_world_args:
    absorbing_state: true
    grid_size: 4
    n_tasks: 80_000
    p_wall: 0.25
  omit_states_actions: 0
train_args:
  alpha: 1
  n_batch: 250
  n_rotations: 1
